// Generated by gencpp from file rvo_ros/SetGoals.msg
// DO NOT EDIT!


#ifndef RVO_ROS_MESSAGE_SETGOALS_H
#define RVO_ROS_MESSAGE_SETGOALS_H

#include <ros/service_traits.h>


#include <rvo_ros/SetGoalsRequest.h>
#include <rvo_ros/SetGoalsResponse.h>


namespace rvo_ros
{

struct SetGoals
{

typedef SetGoalsRequest Request;
typedef SetGoalsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGoals
} // namespace rvo_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rvo_ros::SetGoals > {
  static const char* value()
  {
    return "269a0b03d7a509c517f6ff76c318c9eb";
  }

  static const char* value(const ::rvo_ros::SetGoals&) { return value(); }
};

template<>
struct DataType< ::rvo_ros::SetGoals > {
  static const char* value()
  {
    return "rvo_ros/SetGoals";
  }

  static const char* value(const ::rvo_ros::SetGoals&) { return value(); }
};


// service_traits::MD5Sum< ::rvo_ros::SetGoalsRequest> should match
// service_traits::MD5Sum< ::rvo_ros::SetGoals >
template<>
struct MD5Sum< ::rvo_ros::SetGoalsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rvo_ros::SetGoals >::value();
  }
  static const char* value(const ::rvo_ros::SetGoalsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rvo_ros::SetGoalsRequest> should match
// service_traits::DataType< ::rvo_ros::SetGoals >
template<>
struct DataType< ::rvo_ros::SetGoalsRequest>
{
  static const char* value()
  {
    return DataType< ::rvo_ros::SetGoals >::value();
  }
  static const char* value(const ::rvo_ros::SetGoalsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rvo_ros::SetGoalsResponse> should match
// service_traits::MD5Sum< ::rvo_ros::SetGoals >
template<>
struct MD5Sum< ::rvo_ros::SetGoalsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rvo_ros::SetGoals >::value();
  }
  static const char* value(const ::rvo_ros::SetGoalsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rvo_ros::SetGoalsResponse> should match
// service_traits::DataType< ::rvo_ros::SetGoals >
template<>
struct DataType< ::rvo_ros::SetGoalsResponse>
{
  static const char* value()
  {
    return DataType< ::rvo_ros::SetGoals >::value();
  }
  static const char* value(const ::rvo_ros::SetGoalsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RVO_ROS_MESSAGE_SETGOALS_H
