# mpc
receding: 10
step_time: 0.8  # 保持较低控制频率以减少CPU负载
ref_speed: 0.8  # 参考速度0.4 m/s，接近TEB的max_vel_x: 0.5
device: 'cuda'
time_print: False  # 开启时间打印，监控性能
collision_threshold: 0.2  # 匹配TEB的min_obstacle_dist: 0.2

# robot
robot:
  kinematics: 'diff'
  max_speed: [0.5, 0.4]  # 匹配TEB: max_vel_x: 0.5, max_vel_theta: 0.4
  max_acce: [0.1, 0.1]   # 匹配TEB: acc_lim_x: 0.1, acc_lim_theta: 0.1
  length: 0.65
  width: 0.65

# initial path
ipath:
  interval: 0.15  # 保持适中的路径点间隔
  waypoints: [[0, 0, 0], [0.2, 0, 0]]
  curve_style: 'line'
  min_radius: 0.2
  loop: False
  arrive_threshold: 0.4   # 匹配TEB的xy_goal_tolerance: 0.4
  close_threshold: 0.1    # 保持合理的接近阈值
  arrive_index_threshold: 3
  
# proximal alternating minimization network - 平衡性能和质量
pan:
  iter_num: 10          #  10 适中的迭代次数，平衡性能和质量
  dune_max_num: 100      # 60 适中的障碍物处理数量
  nrmp_max_num: 10       # 8 适中的参考点数量
  dune_checkpoint: None
  iter_threshold: 0.1  # 0.15 适中的收敛阈值

# adjust parameters for real-time tuning - 匹配TRON1特性
adjust:
  q_s: 0.5              # 状态权重
  p_u: 2.0              # 控制权重
  eta: 10.0              # 优化强度，适中设置
  d_max: 1.0            # 最大距离，考虑机器人尺寸
  d_min: 0.4            # 最小距离，匹配TEB的min_obstacle_dist
  # rec_max_num: 8        # 推荐点数量
  # dune_max_num: 12      # DUNE计算数量
  # iter_threshold: 40    # 迭代阈值
